spring.config.import=optional:file:.env[.properties]

spring.application.name=uniportal

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true

spring.mvc.hiddenmethod.filter.enabled=true

spring.liquibase.enabled=true
spring.liquibase.default-schema=public
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml


r2.account-id=${R2_ACCOUNT_ID}
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_KEY}
r2.bucket=${R2_BUCKET}
r2.public-url=${R2_PUBLIC_URL}

server.port=8080
server.address=0.0.0.0

logging.level.liquibase=INFO
logging.level.org.springframework.security=DEBUG