package com.glebzapara.test_project.models;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

public class Group {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;
}

//id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//    faculty INTEGER NOT NULL CHECK(faculty >= 1 AND faculty <= 8),
//    course SMALLINT NOT NULL CHECK (course >= 1 AND course <= 6),
//    speciality VARCHAR(2) NOT NULL CHECK (speciality ~ '[A-Z]+[1-8]'),
//    number SMALLINT NOT NULL,
//    name VARCHAR(10) GENERATED ALWAYS AS (faculty::text || course::text || number::text) STORED,
//    department_id INTEGER REFERENCES departments(id) ON UPDATE CASCADE ON DELETE SET NULL
