package com.glebzapara.test_project.models;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@Table(name = "student_subject_scores")
@Getter
@Setter
@ToString
@NoArgsConstructor
public class StudentSubjectScore {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    @NotNull
    @ManyToOne
    @JoinColumn(name = "student_id", nullable = false)
    private Student student;

    @NotNull
    @ManyToOne
    @JoinColumn(name = "subject_id", nullable = false)
    private Subject subject;

    @NotNull
    @Column(name = "total_score", nullable = false)
    private Integer totalScore = 0;

    @NotNull
    @Column(name = "passed", nullable = false)
    private Boolean passed = false;
}
//id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//    student_id INTEGER NOT NULL REFERENCES students(id) ON UPDATE CASCADE ON DELETE CASCADE,
//    subject_id INTEGER NOT NULL REFERENCES subjects(id) ON UPDATE CASCADE ON DELETE CASCADE,
//    total_score INTEGER NOT NULL DEFAULT 0,
//    passed BOOLEAN NOT NULL DEFAULT FALSE,
//    UNIQUE(student_id, subject_id)